// Random C++ Code Generated by AI Assistant
#include <iostream>
using namespace std;

int main() {
  int a = 5;
  double b = 10.2;
  char c = 'A';
  cout << "The value of a is: " << a << endl;
  cout << "The value of b is: " << b << endl;
  cout << "The value of c is: " << c << endl;
  return 0;
}
